### Get repository rulesets
GET https://api.github.com/repos/tokenize-inc/protocol/rulesets
Accept: application/vnd.github+json
Authorization: Bearer {{ auth_token }}
X-GitHub-Api-Version: 2022-11-28

### Get a specific ruleset
GET https://api.github.com/repos/tokenize-inc/protocol/rulesets/24414
Accept: application/vnd.github+json
Authorization: Bearer {{ auth_token }}
X-GitHub-Api-Version: 2022-11-28
